name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Show versions
        run: |
          node -v
          yarn -v

      - name: Install dependencies
        run: |
          yarn install --network-timeout 600000

      - name: Rebuild native deps for Electron
        run: |
          yarn electron-builder install-app-deps

      - name: Build Windows NSIS installer
        run: |
          yarn build

      - name: Upload artifacts (installer and unpacked)
        uses: actions/upload-artifact@v4
        with:
          name: PDV-Installer
          path: |
            dist/**
